apiVersion: intel.com/v1alpha1
kind: NetworkClusterPolicy
metadata:
  name: netconf-gaudi-scale-out-l3-pfc-lldpad
spec:
  configurationType: gaudi-so
  gaudiScaleOut:
    layer: L3
    pfcPriorities: "11110000"
    enableLLDPAD: true
    image: intel/intel-network-linkdiscovery:latest
    pullPolicy: IfNotPresent
  logLevel: 1
  nodeSelector:
    intel.feature.node.kubernetes.io/gaudi-ready: "true"
