# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: intel-network-tools-metrics
  namespace: intel-network-operator
  labels:
    app: intel-network-tools-metrics
    release: prom
spec:
  selector:
    matchLabels:
      app: intel-network-tools-metrics-service
  endpoints:
  - path: /metrics
    port: metrics-port
