{{- if .Values.config.gaudi.networkMetrics }}
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: intel-network-tools-metrics
  namespace: {{ .Release.Namespace }}
  labels:
{{- with .Values.prometheus.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: intel-network-tools-metrics-service
  endpoints:
  - path: /metrics
    port: metrics-port
{{- end -}}