{{- if .Values.config.gaudi.networkMetrics }}
apiVersion: v1
kind: Service
metadata:
  name: intel-network-tools-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: intel-network-tools-metrics-service
spec:
  selector:
    app: intel-network-tools
  ports:
  - name: metrics-port
    port: 50152
{{- end }}
